/**
 * PetPrep API Schema — Auto-generated TypeScript definitions
 * Generated by: npm run generate-api-types
 * Source: http://127.0.0.1:8266/docs/api.json
 *
 * DO NOT EDIT MANUALLY — regenerate via npm run generate-api-types
 */

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate a user with e-mail + password and issue a Sanctum API
         *     token. The token carries one ability (M2-03): `parent` or `child`
         * @description Children: only legacy child accounts that still have an e-mail and a
         *     password can sign in here (**deprecated**, dev/test accounts until they
         *     are migrated). PIN-only child profiles (M2-02) have neither and use
         *     `POST /api/child/pin-login`; this endpoint answers them like any wrong
         *     credentials (401).
         *
         *     POST /api/login
         */
        post: operations["auth.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the authenticated user's profile (session restore on app launch)
         * @description `awaiting_contract` (also inside `pet`) is evaluated for the signed-in
         *     child: the pet is unborn, or the child joined a shared pet and hasn't
         *     signed their own contract yet. null for a parent.
         *
         *     GET /api/user
         */
        get: operations["auth.user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the current API token (logout)
         * @description POST /api/logout
         */
        post: operations["auth.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/broadcasting/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Authenticate the request for channel access */
        get: operations["broadcast.authenticate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/child/pin-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign a child in with the one-time PIN their parent generated for them
         *     (`POST /api/parent/generate-pin {child_id, pet_id?}`). Unauthenticated
         * @description First use pairs the child (new unborn pet, or joins the shared pet —
         *     `awaiting_contract` true until the child signs); a PIN for an already
         *     paired child only signs in another device (`mode: relogin`). The token
         *     has the ability `child`; a child keeps at most 3 signed-in devices (the
         *     oldest token is revoked).
         *
         *     422 `invalid_pin` (wrong, expired or used — same answer for all),
         *     422 `pin_not_usable` (the family changed since the PIN was issued),
         *     429 `too_many_attempts` (`retry_after` seconds).
         *
         *     POST /api/child/pin-login
         */
        post: operations["childAuth.pinLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/child/contract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Store the child's finger signature once per pet: 201 with the state,
         *     409 `contract_already_signed` for a second signature (the first stays)
         * @description POST /api/child/contract
         */
        post: operations["childContract.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/child/pet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full pet state: displayed metrics, lock, feed windows, water, steps, contract
         * @description GET /api/child/pet
         */
        get: operations["childPet.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/child/pet/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Feed inside a breed feed window (family-local), once per window → hunger 100 %
         * @description POST /api/child/pet/feed
         */
        post: operations["childPet.feed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/child/pet/water": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fresh water (limit per family-local day, minimum gap) → thirst 100 %
         * @description POST /api/child/pet/water
         */
        post: operations["childPet.water"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/child/pet/clean": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cleaning mini-game finished → hygiene 100 %
         * @description POST /api/child/pet/clean
         */
        post: operations["childPet.clean"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/child/pet/steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Step sync: today's cumulative count from HealthKit / Health Connect.
         *     status: accepted | capped (anti-cheat kept part) | rejected | unchanged | stale
         * @description POST /api/child/pet/steps
         */
        post: operations["childPet.steps"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parent/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a child profile in the parent's family: nickname (≤ 30
         *     characters) and optional birth year — no e-mail, no password, no
         *     surname. Then `POST /api/parent/generate-pin {child_id}` gives the
         *     child a one-time PIN for `POST /api/child/pin-login`.
         *     422 `too_many_children` (10 per family)
         * @description POST /api/parent/children
         */
        post: operations["childProfile.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parent/children/{child}/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Sign the child out on every device (deletes all their tokens) and
         *     revoke their open login PIN. 404 for a child outside the family
         * @description DELETE /api/parent/children/{child}/tokens
         */
        delete: operations["childProfile.revokeTokens"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/fal-ai": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Handle a fal.ai webhook (video generation finished or failed)
         * @description 1. The ED25519 signature is verified in FalAiWebhookRequest::authorize() — fail closed.
         *     2. Match the request_id to a job we created (pet_media_jobs); the pet comes
         *        from that job, never from client-supplied parameters.
         *     3. Idempotent: a job is finalised once; repeats are acknowledged.
         *     4. On success, set the pet's current video and broadcast once.
         *
         *     POST /api/webhooks/fal-ai
         */
        post: operations["falAiWebhook.handle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parent/invite-parent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an invite code for another parent: 8 characters, valid 24 h,
         *     single use. A new code revokes this parent's previous unused one
         * @description POST /api/parent/invite-parent
         */
        post: operations["family.invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parent/join-family": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join the inviting family as a parent. Allowed only for a parent account
         *     without children or pets of its own (409 `family_not_empty`).
         *     422 `invalid_code` | `code_expired` | `code_used`; 409 `already_member`;
         *     429 `too_many_attempts` after 5 wrong codes in 15 minutes
         * @description POST /api/parent/join-family
         */
        post: operations["family.join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parent/generate-pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate a 6-digit, one-time child PIN (15 minutes)
         * @description With `child_id` (M2-02, preferred): the PIN is for that child profile
         *     of the family and is used on the child's device with
         *     `POST /api/child/pin-login` (no e-mail, no password). `mode` says what
         *     it will do: `new_pet` (first pairing), `join_pet` (with `pet_id`: the
         *     child joins that shared pet), `relogin` (already paired child, new
         *     device). A new PIN for the child replaces their previous one.
         *     404 `child_not_found`, 422 `pet_not_joinable` | `already_paired`.
         *
         *     Without `child_id` (**deprecated**, `Deprecation: true` header): the
         *     PIN is for a child already signed in with e-mail, used with
         *     `POST /api/child/pair`; optional `pet_id` = join that pet.
         *
         *     POST /api/parent/generate-pin
         */
        post: operations["pairing.generatePin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/child/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pair a child using a parent's PIN. New-pet PIN: creates the child's
         *     pet — unborn (`born_at` null) until POST /api/child/contract. Join PIN
         *     (M2-01): the child becomes a caretaker of the existing pet
         *     (`joined_existing` true); the pet is not re-born, but this child must
         *     sign their own contract (`awaiting_contract` true for them)
         * @description **Deprecated (M2-02):** only for children with an e-mail account; new
         *     child profiles sign in with `POST /api/child/pin-login`.
         *
         *     POST /api/child/pair
         */
        post: operations["pairing.pairChild"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parent/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /api/parent/dashboard
         *     Family (parents, children with per-child 7-day stats, pets with
         *     caretakers) + legacy single-pet state, traffic light, quiet hours,
         *     recent activities
         */
        get: operations["parentDashboard.dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parent/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /api/parent/activities?pet_id=
         *     Paginated activity logs for the timeline of one pet of the family
         *     (default: the legacy pet). Each item names the acting child
         *     (`actor_user_id`, null for system events)
         */
        get: operations["parentDashboard.activities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parent/hard-stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST /api/parent/hard-stop {pet_id?}
         *     Toggles hard stop on one active pet of the family (default: the legacy
         *     pet) and broadcasts PetUpdated. Any parent of the family may do it
         */
        post: operations["parentDashboard.toggleHardStop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parent/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update family settings (currently the family timezone)
         * @description PUT /api/parent/settings
         */
        put: operations["parentSettings.update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parent/quiet-hours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the family's quiet hours (one configuration per family; any
         *     parent of the family reads and edits it — M2-01)
         * @description GET /api/parent/quiet-hours
         */
        get: operations["quietHours.show"];
        /**
         * Create or update the quiet hours configuration for the authenticated parent
         * @description PUT /api/parent/quiet-hours
         */
        put: operations["quietHours.update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/revenuecat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST /api/webhooks/revenuecat
         *     Handle RevenueCat webhook events for successful purchases
         * @description Validates the payload using the RevenueCatWebhookRequest Form Request,
         *     verifies the Authorization header against the configured secret,
         *     updates users.revenuecat_id, unlocks the premium breed
         *     (Border Collie) in the pets table, and broadcasts the
         *     update via Laravel Reverb.
         */
        post: operations["revenueCatWebhook.handle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BreedType
         * @enum {string}
         */
        BreedType: "mutt" | "border_collie";
        /**
         * CreateChildRequest
         * @description POST /api/parent/children (M2-02). Minimal data about a minor: a nickname
         *     (no surname needed) and an optional birth year — no e-mail, no birthdate.
         */
        CreateChildRequest: {
            /**
             * @description Letters (any script), digits, spaces, hyphen, apostrophe, dot.
             *     No "@": a nickname, not an e-mail address.
             */
            display_name: string;
            /** @description Under 18 (a child profile); optional. */
            birth_year?: number | null;
        };
        /** FalAiWebhookRequest */
        FalAiWebhookRequest: {
            request_id: string;
            /** @enum {string} */
            status: "OK" | "ERROR";
            payload?: string[] | null;
            error?: string | null;
        };
        /** GeneratePinRequest */
        GeneratePinRequest: {
            /**
             * @description M2-02: the child profile the PIN is for (POST /api/child/pin-login).
             *     Omitted = deprecated flow (the child is already signed in with
             *     e-mail and calls POST /api/child/pair).
             */
            child_id?: number | null;
            /**
             * @description Family model (M2-01): omit for a new pet; an existing pet of
             *     the family = the child will share it (shared custody).
             */
            pet_id?: number | null;
        };
        /** JoinFamilyRequest */
        JoinFamilyRequest: {
            /** @description 8 characters; case and surrounding spaces are forgiven. */
            code: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
            device_name?: string | null;
        };
        /** PairChildRequest */
        PairChildRequest: {
            pin: string;
        };
        /** PairedPetResource */
        PairedPetResource: {
            id: number;
            breed_type: string;
            hunger_level: number;
            thirst_level: number;
            energy_level: number;
            hygiene_level: number;
            /** @description null until the first contract is signed (M1-07b). */
            born_at: string | null;
            /**
             * @description This child must sign before acting (new unborn pet, or joined a
             *     shared pet and has not signed yet).
             */
            awaiting_contract: boolean;
            is_active: boolean;
            is_game_over: boolean;
            pet_dna: {
                seed: string | null;
                prompt_anchor: string | null;
                visual_traits: string | null;
                reference_image_url: string | null;
            };
            current_video_url: string | null;
            media_status: string;
        };
        /** Pet */
        Pet: {
            id: number;
            user_id: number;
            breed_type: components["schemas"]["BreedType"];
            hunger_level: number;
            energy_level: number;
            hygiene_level: number;
            /** Format: date-time */
            born_at: string | null;
            is_active: boolean;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
            pet_dna: unknown[] | null;
            current_video_url: string | null;
            pet_state: components["schemas"]["PetStateEnum"];
            thirst_level: number;
            /** Format: date-time */
            illness_until: string | null;
            daily_step_count: number;
            /** Format: date-time */
            last_step_reset_at: string | null;
            escalation_level: number;
            /** Format: date-time */
            hunger_zero_since: string | null;
            /** Format: date-time */
            thirst_zero_since: string | null;
            /** Format: date-time */
            energy_zero_since: string | null;
            /** Format: date-time */
            hygiene_zero_since: string | null;
            is_game_over: boolean;
            certificate_eligible: boolean;
            is_hard_stopped: boolean;
            media_status: string;
            /** Format: date-time */
            last_decay_at: string | null;
            /** Format: date-time */
            frozen_at: string | null;
            /** Format: date-time */
            last_step_sync_at: string | null;
            hygiene_scheduled_through: string | null;
            /** Format: date-time */
            walk_illness_due_at: string | null;
            family_id: number;
        };
        /**
         * PetStateEnum
         * @description Represents the visual/behavioral state of a pet. Each state maps to a specific video asset generated by fal.ai (Kling 3.0).
         * @enum {string}
         */
        PetStateEnum: "idle" | "sleeping" | "low_energy" | "hungry" | "sick" | "playing";
        /**
         * PinLoginRequest
         * @description POST /api/child/pin-login (M2-02) — unauthenticated.
         */
        PinLoginRequest: {
            pin: string;
            device_name: string;
        };
        /** QuietHours */
        QuietHours: {
            id: number;
            parent_id: number;
            school_start: string | null;
            school_end: string | null;
            bedtime_start: string | null;
            bedtime_end: string | null;
            is_active: boolean;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
            family_id: number | null;
        };
        /** RevenueCatWebhookRequest */
        RevenueCatWebhookRequest: {
            event: {
                type: string;
                app_user_id: string;
                subscriber_id?: string | null;
                original_app_user_id?: string | null;
                product_id?: string | null;
                store?: string | null;
            };
        };
        /**
         * SignContractRequest
         * @description POST /api/child/contract (M1-07, PRODUCT_SPEC §3): the child's finger
         *     signature, either
         *      - `svg_path`: SVG path data (commands M L H V C S Q T A Z and numbers
         *        only, must start with a move), at most 20,000 characters; or
         *      - `png`: base64 PNG (an optional `data:image/png;base64,` prefix is
         *        stripped), at most 100 KB decoded, PNG signature checked.
         *     No external calls; `signed_at` is set by the server.
         */
        SignContractRequest: {
            /** @enum {string} */
            signature_format: "svg_path" | "png";
            signature: string;
        };
        /**
         * SyncStepsRequest
         * @description POST /api/child/pet/steps (M1-04 / M1-07): today's cumulative step count
         *     from the phone. The service handles idempotency (max wins), anti-cheat and
         *     stale days; `source` is validated but not stored (data minimisation).
         */
        SyncStepsRequest: {
            steps_today: number;
            /** @enum {string} */
            source: "healthkit" | "health_connect" | "pedometer";
            /**
             * Format: date-time
             * @description Strict ISO 8601 with an explicit offset: the server must not guess
             *     the device's zone. Accepts 2026-10-04T15:30:00+02:00, …Z and
             *     fractional seconds (…15:30:00.123Z); rejects "now", "yesterday",
             *     date-only and offset-less strings.
             */
            recorded_at: string;
        };
        /** UpdateParentSettingsRequest */
        UpdateParentSettingsRequest: {
            /** @description IANA identifier, case-sensitive (e.g. "Europe/Ljubljana"). */
            timezone: string;
        };
        /** UpdateQuietHoursRequest */
        UpdateQuietHoursRequest: {
            school_start?: string | null;
            school_end?: string | null;
            bedtime_start?: string | null;
            bedtime_end?: string | null;
            is_active?: boolean;
            /** @description Optional family timezone (IANA), saved on the parent (M1-03). */
            timezone?: string;
        };
    };
    responses: {
        /** @description Validation error */
        ValidationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Errors overview. */
                    message: string;
                    /** @description A detailed description of each field that failed validation. */
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
        /** @description Unauthenticated */
        AuthenticationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Authorization error */
        AuthorizationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "auth.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: string;
                        abilities: [
                            string
                        ];
                        user: {
                            id: number;
                            name: string;
                            email: string | null;
                            role: string;
                        };
                        pet: components["schemas"]["Pet"] | null;
                        /** @description Per child (M2-02): this child must sign before acting. null for a parent. */
                        awaiting_contract: boolean | null;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Invalid credentials.";
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        name: string;
                        email: string | null;
                        role: string;
                        pet: components["schemas"]["Pet"] | null;
                        awaiting_contract: boolean | null;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "auth.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Logged out successfully.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "broadcast.authenticate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "childAuth.pinLogin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinLoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: string;
                        abilities: [
                            string
                        ];
                        /** @description Only the nickname — the profile has no e-mail. */
                        user: {
                            id: number;
                            name: string;
                            role: string;
                        };
                        /** @enum {string} */
                        mode: "join_pet" | "new_pet" | "relogin";
                        joined_existing: string;
                        family_id: string;
                        pet: components["schemas"]["PairedPetResource"];
                        awaiting_contract: boolean;
                    } | string;
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "childContract.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignContractRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "The pet is locked right now.";
                        status: string;
                        reason: string | null;
                        /** @description End of the vet visit; null for locks without an end time. */
                        locked_until: string | null;
                        state: {
                            pet: {
                                id: number;
                                breed_type: string;
                                /** @description null until the first contract is signed (unborn, M1-07b). */
                                born_at: string | null;
                                /**
                                 * @description This child must sign before acting (pet unborn, or this
                                 *     child joined a shared pet and hasn't signed yet — M2-01).
                                 */
                                awaiting_contract: boolean;
                                caretakers_count: number;
                                virtual_age_months: number;
                                hunger_level: number;
                                thirst_level: number;
                                energy_level: number;
                                hygiene_level: number;
                                pet_state: string;
                                escalation_level: number;
                                needs_cleaning: boolean;
                                is_active: boolean;
                                is_hard_stopped: boolean;
                                is_ill: boolean;
                                illness_until: string | null;
                                is_game_over: boolean;
                                certificate_eligible: boolean;
                                current_video_url: string | null;
                                media_status: string;
                                reference_image_url: string | null;
                            };
                            lock: {
                                is_locked: boolean;
                                /** @description game_over | inactive | hard_stopped | contract_required | ill | null */
                                reason: string | null;
                                /** @description End of the vet visit; null for locks without an end time. */
                                until: string | null;
                            };
                            timezone: string;
                            server_time: string;
                            feeding: {
                                windows: unknown[];
                                current_window: {
                                    start: string;
                                    end: string;
                                } | null;
                                fed_in_current_window: boolean;
                                can_feed: string;
                                /** @description The current window while unused, otherwise the next one. */
                                next_feed_window: {
                                    start: string;
                                    end: string;
                                } | null;
                                last_fed_at: string;
                            };
                            water: {
                                times_per_day: string | 0;
                                min_gap_minutes: string | 0;
                                used_today: string | 0;
                                remaining_today: string | 0;
                                last_watered_at: string;
                                can_water: string;
                                /** @description Earliest next refill by the water rules; null when allowed now. */
                                next_allowed_at: string;
                            };
                            steps: {
                                steps_today: number;
                                my_steps_today: number;
                                goal: number;
                                energy_level: number;
                            };
                            contract: {
                                signed: boolean;
                                signed_at: string;
                            };
                        };
                    };
                };
            };
        };
    };
    "childPet.show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        pet: {
                            id: number;
                            breed_type: string;
                            /** @description null until the first contract is signed (unborn, M1-07b). */
                            born_at: string | null;
                            /**
                             * @description This child must sign before acting (pet unborn, or this
                             *     child joined a shared pet and hasn't signed yet — M2-01).
                             */
                            awaiting_contract: boolean;
                            caretakers_count: number;
                            virtual_age_months: number;
                            hunger_level: number;
                            thirst_level: number;
                            energy_level: number;
                            hygiene_level: number;
                            pet_state: string;
                            escalation_level: number;
                            needs_cleaning: boolean;
                            is_active: boolean;
                            is_hard_stopped: boolean;
                            is_ill: boolean;
                            illness_until: string | null;
                            is_game_over: boolean;
                            certificate_eligible: boolean;
                            current_video_url: string | null;
                            media_status: string;
                            reference_image_url: string | null;
                        };
                        lock: {
                            is_locked: boolean;
                            /** @description game_over | inactive | hard_stopped | contract_required | ill | null */
                            reason: string | null;
                            /** @description End of the vet visit; null for locks without an end time. */
                            until: string | null;
                        };
                        timezone: string;
                        server_time: string;
                        feeding: {
                            windows: unknown[];
                            current_window: {
                                start: string;
                                end: string;
                            } | null;
                            fed_in_current_window: boolean;
                            can_feed: string;
                            /** @description The current window while unused, otherwise the next one. */
                            next_feed_window: {
                                start: string;
                                end: string;
                            } | null;
                            last_fed_at: string;
                        };
                        water: {
                            times_per_day: string | 0;
                            min_gap_minutes: string | 0;
                            used_today: string | 0;
                            remaining_today: string | 0;
                            last_watered_at: string;
                            can_water: string;
                            /** @description Earliest next refill by the water rules; null when allowed now. */
                            next_allowed_at: string;
                        };
                        steps: {
                            steps_today: number;
                            my_steps_today: number;
                            goal: number;
                            energy_level: number;
                        };
                        contract: {
                            signed: boolean;
                            signed_at: string;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "childPet.feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[] | string;
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "The pet is locked right now.";
                        status: string;
                        reason: string | null;
                        /** @description End of the vet visit; null for locks without an end time. */
                        locked_until: string | null;
                        state: {
                            pet: {
                                id: number;
                                breed_type: string;
                                /** @description null until the first contract is signed (unborn, M1-07b). */
                                born_at: string | null;
                                /**
                                 * @description This child must sign before acting (pet unborn, or this
                                 *     child joined a shared pet and hasn't signed yet — M2-01).
                                 */
                                awaiting_contract: boolean;
                                caretakers_count: number;
                                virtual_age_months: number;
                                hunger_level: number;
                                thirst_level: number;
                                energy_level: number;
                                hygiene_level: number;
                                pet_state: string;
                                escalation_level: number;
                                needs_cleaning: boolean;
                                is_active: boolean;
                                is_hard_stopped: boolean;
                                is_ill: boolean;
                                illness_until: string | null;
                                is_game_over: boolean;
                                certificate_eligible: boolean;
                                current_video_url: string | null;
                                media_status: string;
                                reference_image_url: string | null;
                            };
                            lock: {
                                is_locked: boolean;
                                /** @description game_over | inactive | hard_stopped | contract_required | ill | null */
                                reason: string | null;
                                /** @description End of the vet visit; null for locks without an end time. */
                                until: string | null;
                            };
                            timezone: string;
                            server_time: string;
                            feeding: {
                                windows: unknown[];
                                current_window: {
                                    start: string;
                                    end: string;
                                } | null;
                                fed_in_current_window: boolean;
                                can_feed: string;
                                /** @description The current window while unused, otherwise the next one. */
                                next_feed_window: {
                                    start: string;
                                    end: string;
                                } | null;
                                last_fed_at: string;
                            };
                            water: {
                                times_per_day: string | 0;
                                min_gap_minutes: string | 0;
                                used_today: string | 0;
                                remaining_today: string | 0;
                                last_watered_at: string;
                                can_water: string;
                                /** @description Earliest next refill by the water rules; null when allowed now. */
                                next_allowed_at: string;
                            };
                            steps: {
                                steps_today: number;
                                my_steps_today: number;
                                goal: number;
                                energy_level: number;
                            };
                            contract: {
                                signed: boolean;
                                signed_at: string;
                            };
                        };
                    };
                };
            };
        };
    };
    "childPet.water": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[] | string;
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "The pet is locked right now.";
                        status: string;
                        reason: string | null;
                        /** @description End of the vet visit; null for locks without an end time. */
                        locked_until: string | null;
                        state: {
                            pet: {
                                id: number;
                                breed_type: string;
                                /** @description null until the first contract is signed (unborn, M1-07b). */
                                born_at: string | null;
                                /**
                                 * @description This child must sign before acting (pet unborn, or this
                                 *     child joined a shared pet and hasn't signed yet — M2-01).
                                 */
                                awaiting_contract: boolean;
                                caretakers_count: number;
                                virtual_age_months: number;
                                hunger_level: number;
                                thirst_level: number;
                                energy_level: number;
                                hygiene_level: number;
                                pet_state: string;
                                escalation_level: number;
                                needs_cleaning: boolean;
                                is_active: boolean;
                                is_hard_stopped: boolean;
                                is_ill: boolean;
                                illness_until: string | null;
                                is_game_over: boolean;
                                certificate_eligible: boolean;
                                current_video_url: string | null;
                                media_status: string;
                                reference_image_url: string | null;
                            };
                            lock: {
                                is_locked: boolean;
                                /** @description game_over | inactive | hard_stopped | contract_required | ill | null */
                                reason: string | null;
                                /** @description End of the vet visit; null for locks without an end time. */
                                until: string | null;
                            };
                            timezone: string;
                            server_time: string;
                            feeding: {
                                windows: unknown[];
                                current_window: {
                                    start: string;
                                    end: string;
                                } | null;
                                fed_in_current_window: boolean;
                                can_feed: string;
                                /** @description The current window while unused, otherwise the next one. */
                                next_feed_window: {
                                    start: string;
                                    end: string;
                                } | null;
                                last_fed_at: string;
                            };
                            water: {
                                times_per_day: string | 0;
                                min_gap_minutes: string | 0;
                                used_today: string | 0;
                                remaining_today: string | 0;
                                last_watered_at: string;
                                can_water: string;
                                /** @description Earliest next refill by the water rules; null when allowed now. */
                                next_allowed_at: string;
                            };
                            steps: {
                                steps_today: number;
                                my_steps_today: number;
                                goal: number;
                                energy_level: number;
                            };
                            contract: {
                                signed: boolean;
                                signed_at: string;
                            };
                        };
                    };
                };
            };
        };
    };
    "childPet.clean": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[] | string;
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "The pet is locked right now.";
                        status: string;
                        reason: string | null;
                        /** @description End of the vet visit; null for locks without an end time. */
                        locked_until: string | null;
                        state: {
                            pet: {
                                id: number;
                                breed_type: string;
                                /** @description null until the first contract is signed (unborn, M1-07b). */
                                born_at: string | null;
                                /**
                                 * @description This child must sign before acting (pet unborn, or this
                                 *     child joined a shared pet and hasn't signed yet — M2-01).
                                 */
                                awaiting_contract: boolean;
                                caretakers_count: number;
                                virtual_age_months: number;
                                hunger_level: number;
                                thirst_level: number;
                                energy_level: number;
                                hygiene_level: number;
                                pet_state: string;
                                escalation_level: number;
                                needs_cleaning: boolean;
                                is_active: boolean;
                                is_hard_stopped: boolean;
                                is_ill: boolean;
                                illness_until: string | null;
                                is_game_over: boolean;
                                certificate_eligible: boolean;
                                current_video_url: string | null;
                                media_status: string;
                                reference_image_url: string | null;
                            };
                            lock: {
                                is_locked: boolean;
                                /** @description game_over | inactive | hard_stopped | contract_required | ill | null */
                                reason: string | null;
                                /** @description End of the vet visit; null for locks without an end time. */
                                until: string | null;
                            };
                            timezone: string;
                            server_time: string;
                            feeding: {
                                windows: unknown[];
                                current_window: {
                                    start: string;
                                    end: string;
                                } | null;
                                fed_in_current_window: boolean;
                                can_feed: string;
                                /** @description The current window while unused, otherwise the next one. */
                                next_feed_window: {
                                    start: string;
                                    end: string;
                                } | null;
                                last_fed_at: string;
                            };
                            water: {
                                times_per_day: string | 0;
                                min_gap_minutes: string | 0;
                                used_today: string | 0;
                                remaining_today: string | 0;
                                last_watered_at: string;
                                can_water: string;
                                /** @description Earliest next refill by the water rules; null when allowed now. */
                                next_allowed_at: string;
                            };
                            steps: {
                                steps_today: number;
                                my_steps_today: number;
                                goal: number;
                                energy_level: number;
                            };
                            contract: {
                                signed: boolean;
                                signed_at: string;
                            };
                        };
                    };
                };
            };
        };
    };
    "childPet.steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncStepsRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[] | string;
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "The pet is locked right now.";
                        status: string;
                        reason: string | null;
                        /** @description End of the vet visit; null for locks without an end time. */
                        locked_until: string | null;
                        state: {
                            pet: {
                                id: number;
                                breed_type: string;
                                /** @description null until the first contract is signed (unborn, M1-07b). */
                                born_at: string | null;
                                /**
                                 * @description This child must sign before acting (pet unborn, or this
                                 *     child joined a shared pet and hasn't signed yet — M2-01).
                                 */
                                awaiting_contract: boolean;
                                caretakers_count: number;
                                virtual_age_months: number;
                                hunger_level: number;
                                thirst_level: number;
                                energy_level: number;
                                hygiene_level: number;
                                pet_state: string;
                                escalation_level: number;
                                needs_cleaning: boolean;
                                is_active: boolean;
                                is_hard_stopped: boolean;
                                is_ill: boolean;
                                illness_until: string | null;
                                is_game_over: boolean;
                                certificate_eligible: boolean;
                                current_video_url: string | null;
                                media_status: string;
                                reference_image_url: string | null;
                            };
                            lock: {
                                is_locked: boolean;
                                /** @description game_over | inactive | hard_stopped | contract_required | ill | null */
                                reason: string | null;
                                /** @description End of the vet visit; null for locks without an end time. */
                                until: string | null;
                            };
                            timezone: string;
                            server_time: string;
                            feeding: {
                                windows: unknown[];
                                current_window: {
                                    start: string;
                                    end: string;
                                } | null;
                                fed_in_current_window: boolean;
                                can_feed: string;
                                /** @description The current window while unused, otherwise the next one. */
                                next_feed_window: {
                                    start: string;
                                    end: string;
                                } | null;
                                last_fed_at: string;
                            };
                            water: {
                                times_per_day: string | 0;
                                min_gap_minutes: string | 0;
                                used_today: string | 0;
                                remaining_today: string | 0;
                                last_watered_at: string;
                                can_water: string;
                                /** @description Earliest next refill by the water rules; null when allowed now. */
                                next_allowed_at: string;
                            };
                            steps: {
                                steps_today: number;
                                my_steps_today: number;
                                goal: number;
                                energy_level: number;
                            };
                            contract: {
                                signed: boolean;
                                signed_at: string;
                            };
                        };
                    };
                };
            };
        };
    };
    "childProfile.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChildRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        child: {
                            id: number;
                            display_name: string;
                            birth_year: number | null;
                            family_id: number;
                            pet_id: null;
                            devices: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "childProfile.revokeTokens": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                child: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        revoked_tokens: number;
                        revoked_pins: number;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            /** @description An error */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Error overview.
                         * @example
                         */
                        message: string;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "No such child in your family.";
                        /** @constant */
                        reason: "child_not_found";
                    };
                };
            };
        };
    };
    "falAiWebhook.handle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FalAiWebhookRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Video URL updated successfully.";
                        pet_id: number;
                    } | {
                        /** @constant */
                        message: "Failure recorded.";
                    } | {
                        /** @constant */
                        message: "Already processed.";
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Unauthorized";
                    };
                };
            };
            403: components["responses"]["AuthorizationException"];
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Unknown request.";
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "family.invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        expires_at: string;
                        /** @constant */
                        expires_in_hours: 24;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "family.join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinFamilyRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "You joined the family.";
                        family: {
                            id: number;
                            timezone: string;
                            parents: string;
                            children_count: number;
                            pets_count: number;
                        };
                    } | string;
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "pairing.generatePin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["GeneratePinRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    Deprecation?: "true";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        pin: string;
                        expires_at: string;
                        /** @constant */
                        expires_in_minutes: 15;
                        child_id: null;
                        /** @description null = new pet; otherwise the pet the child will join. */
                        pet_id: number | null;
                        /** @enum {string} */
                        mode: "new_pet" | "join_pet";
                    } | string | {
                        pin: string;
                        expires_at: string;
                        /** @constant */
                        expires_in_minutes: 15;
                        child_id: number;
                        /** @description null = new pet (or re-login); otherwise the pet to join. */
                        pet_id: number | null;
                        /** @enum {string} */
                        mode: "join_pet" | "new_pet" | "relogin";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "pairing.pairChild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairChildRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Pairing successful. Pet session initialized.";
                        parent_id: number;
                        family_id: string;
                        joined_existing: string;
                        pet: components["schemas"]["PairedPetResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "parentDashboard.dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        timezone: string;
                        pet: {
                            id: number;
                            breed_type: string;
                            /**
                             * @description Contract before birth (M1-07b): until the first contract,
                             *     born_at is null and awaiting_contract true (metrics 100,
                             *     nothing decays, no alerts).
                             */
                            born_at: string | null;
                            awaiting_contract: boolean;
                            hunger_level: number;
                            thirst_level: number;
                            energy_level: number;
                            hygiene_level: number;
                            pet_state: string;
                            is_active: boolean;
                            is_ill: boolean;
                            is_game_over: boolean;
                            is_hard_stopped: boolean;
                            escalation_level: number;
                            virtual_age_months: number;
                            current_video_url: string | null;
                        };
                        child: {
                            id: number;
                            name: string;
                        } | null;
                        /** @enum {string} */
                        traffic_light: "green" | "amber" | "red";
                        quiet_hours: {
                            school_start: string | null;
                            school_end: string | null;
                            bedtime_start: string | null;
                            bedtime_end: string | null;
                            is_active: boolean;
                        } | null;
                        recent_activities: {
                            id: string;
                            activity_type: string;
                            value: string;
                            /** @description The child who did it (M2-01); null for system events. */
                            actor_user_id: string;
                            created_at: string | null;
                            is_positive: boolean;
                        }[];
                        weekly_performance: {
                            date: string;
                            completed: number;
                            missed: number;
                        }[];
                        family: {
                            id: number;
                            timezone: string;
                            parents: string;
                            children: string;
                            pets: {
                                id: number;
                                breed_type: string;
                                born_at: string | null;
                                awaiting_contract: boolean;
                                is_active: boolean;
                                is_game_over: boolean;
                                is_hard_stopped: boolean;
                                is_ill: boolean;
                                /** @enum {string} */
                                traffic_light: "green" | "amber" | "red";
                                caretakers: {
                                    child_id: number;
                                    contract_signed: boolean;
                                }[];
                            }[];
                        };
                    } | {
                        /** @enum {string} */
                        message: "No active pet session found." | "No child profile paired yet.";
                        timezone: string;
                        pet: null;
                        /** @constant */
                        traffic_light: "green";
                        quiet_hours: components["schemas"]["QuietHours"] | null;
                        recent_activities: string[];
                        family: {
                            id: number;
                            timezone: string;
                            parents: string;
                            children: string;
                            pets: {
                                id: number;
                                breed_type: string;
                                born_at: string | null;
                                awaiting_contract: boolean;
                                is_active: boolean;
                                is_game_over: boolean;
                                is_hard_stopped: boolean;
                                is_ill: boolean;
                                /** @enum {string} */
                                traffic_light: "green" | "amber" | "red";
                                caretakers: {
                                    child_id: number;
                                    contract_signed: boolean;
                                }[];
                            }[];
                        };
                    } | {
                        /** @constant */
                        message: "No child profile paired yet.";
                        timezone: string;
                        pet: null;
                        /** @constant */
                        traffic_light: "green";
                        quiet_hours: null;
                        recent_activities: string[];
                        family: null;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Only parent profiles can access the dashboard.";
                    };
                };
            };
        };
    };
    "parentDashboard.activities": {
        parameters: {
            query?: {
                pet_id?: number | null;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            activity_type: string;
                            value: string;
                            /** @description The child who did it (M2-01); null for system events. */
                            actor_user_id: string;
                            created_at: string | null;
                            is_positive: boolean;
                        }[];
                        meta: {
                            current_page: number;
                            last_page: number;
                            total: number;
                        };
                    } | {
                        data: string[];
                        meta: {
                            /** @constant */
                            current_page: 1;
                            /** @constant */
                            last_page: 1;
                            total: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Only parent profiles can access activities.";
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Pet not found in your family.";
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "parentDashboard.toggleHardStop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    pet_id?: number | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        message: "Hard stop activated. Child app locked." | "Hard stop deactivated. Child app unlocked.";
                        pet_id: number;
                        is_hard_stopped: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Only parent profiles can trigger hard stop.";
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "No active pet session found.";
                    } | {
                        /** @constant */
                        message: "No child profile paired.";
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "parentSettings.update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateParentSettingsRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Settings updated successfully.";
                        settings: {
                            timezone: string;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "quietHours.show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        quiet_hours: {
                            id: number;
                            school_start: string | null;
                            school_end: string | null;
                            bedtime_start: string | null;
                            bedtime_end: string | null;
                            is_active: boolean;
                        };
                        timezone: string;
                    } | {
                        /** @constant */
                        message: "No quiet hours configured.";
                        quiet_hours: null;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Only parent profiles can manage quiet hours.";
                    };
                };
            };
        };
    };
    "quietHours.update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateQuietHoursRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Quiet hours updated successfully.";
                        quiet_hours: {
                            id: number;
                            school_start: string | null;
                            school_end: string | null;
                            bedtime_start: string | null;
                            bedtime_end: string | null;
                            is_active: boolean;
                        };
                        timezone: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Only parent profiles can manage quiet hours.";
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "revenueCatWebhook.handle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevenueCatWebhookRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Purchase recorded.";
                        revenuecat_id: string | null;
                    } | {
                        /** @constant */
                        message: "Border Collie breed unlocked successfully.";
                        pet_id: number;
                        breed_type: string;
                    } | {
                        /** @constant */
                        message: "Event ignored.";
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Unauthorized";
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "User not found.";
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
}
