/**
 * PetPrep API Schema — Auto-generated TypeScript definitions
 * Generated by: npm run generate-api-types
 * Source: http://localhost:8000/docs/api.json
 *
 * DO NOT EDIT MANUALLY — regenerate via npm run generate-api-types
 */

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description `User` */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["AuthenticationException"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/fal-ai": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Handle incoming fal.ai webhook callbacks
         * @description When a Kling 3.0 video generation job completes, fal.ai calls
         *     this endpoint with the result. We:
         *     1. Validate the webhook secret header
         *     2. Extract the video URL from the payload
         *     3. Update the pet's current_video_url
         *     4. Broadcast a PetUpdated event via Laravel Reverb to the
         *        parent dashboard and child UI in real-time
         *
         *     POST /api/webhooks/fal-ai
         */
        post: operations["falAiWebhook.handle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parent/generate-pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate a 6-digit pairing PIN for the authenticated parent
         * @description POST /api/parent/generate-pin
         */
        post: operations["pairing.generatePin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/child/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pair a child to a parent using a 6-digit PIN.
         *     Initializes the child's pet session atomically
         * @description POST /api/child/pair
         */
        post: operations["pairing.pairChild"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parent/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /api/parent/dashboard
         *     Returns combined state: pet metrics, traffic light status, quiet hours, recent activities
         */
        get: operations["parentDashboard.dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parent/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /api/parent/activities
         *     Paginated activity logs for the timeline
         */
        get: operations["parentDashboard.activities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parent/hard-stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST /api/parent/hard-stop
         *     Toggles hard stop state and broadcasts PetUpdated event
         */
        post: operations["parentDashboard.toggleHardStop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parent/quiet-hours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the quiet hours configuration for the authenticated parent
         * @description GET /api/parent/quiet-hours
         */
        get: operations["quietHours.show"];
        /**
         * Create or update the quiet hours configuration for the authenticated parent
         * @description PUT /api/parent/quiet-hours
         */
        put: operations["quietHours.update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/revenuecat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST /api/webhooks/revenuecat
         *     Handle RevenueCat webhook events for successful purchases
         * @description Validates the payload using the RevenueCatWebhookRequest Form Request,
         *     verifies the Authorization header against the configured secret,
         *     updates users.revenuecat_id, unlocks the premium breed
         *     (Border Collie) in the pets table, and broadcasts the
         *     update via Laravel Reverb.
         */
        post: operations["revenueCatWebhook.handle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** FalAiWebhookRequest */
        FalAiWebhookRequest: {
            request_id: string;
            status: string;
            pet_id?: number | null;
        };
        /** PairChildRequest */
        PairChildRequest: {
            pin: string;
        };
        /** QuietHours */
        QuietHours: {
            id: number;
            parent_id: number;
            school_start: string | null;
            school_end: string | null;
            bedtime_start: string | null;
            bedtime_end: string | null;
            is_active: boolean;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
        };
        /** RevenueCatWebhookRequest */
        RevenueCatWebhookRequest: {
            event: {
                type: string;
                app_user_id: string;
                subscriber_id?: string | null;
                original_app_user_id?: string | null;
                product_id?: string | null;
                store?: string | null;
            };
        };
        /** UpdateQuietHoursRequest */
        UpdateQuietHoursRequest: {
            school_start?: string | null;
            school_end?: string | null;
            bedtime_start?: string | null;
            bedtime_end?: string | null;
            is_active?: boolean;
        };
        /** User */
        User: {
            id: number;
            name: string;
            email: string;
            /** Format: date-time */
            email_verified_at: string | null;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
            role: components["schemas"]["UserRole"];
            parent_id: number | null;
            /** Format: date-time */
            pin_expires_at: string | null;
            is_superadmin: boolean;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "parent" | "child";
    };
    responses: {
        /** @description Unauthenticated */
        AuthenticationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Validation error */
        ValidationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Errors overview. */
                    message: string;
                    /** @description A detailed description of each field that failed validation. */
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "falAiWebhook.handle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FalAiWebhookRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Video URL updated successfully.";
                        pet_id: number;
                        current_video_url: string;
                    } | {
                        /** @constant */
                        message: "Webhook acknowledged (no action needed).";
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Unauthorized";
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Pet not found.";
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "pairing.generatePin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        pin: string;
                        expires_at: string;
                        /** @constant */
                        expires_in_minutes: 15;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Only parent profiles can generate pairing PINs.";
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "pairing.pairChild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairChildRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Pairing successful. Pet session initialized.";
                        parent_id: number;
                        pet: {
                            id: number;
                            breed_type: string;
                            hunger_level: number;
                            energy_level: number;
                            hygiene_level: number;
                            born_at: string;
                            is_active: boolean;
                            pet_dna: {
                                seed: string | null;
                                prompt_anchor: string | null;
                                visual_traits: string | null;
                                reference_image_url: string | null;
                            };
                            current_video_url: string | null;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "parentDashboard.dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        pet: {
                            id: number;
                            breed_type: string;
                            hunger_level: number;
                            thirst_level: number;
                            energy_level: number;
                            hygiene_level: number;
                            pet_state: string;
                            is_active: boolean;
                            is_ill: boolean;
                            is_game_over: boolean;
                            is_hard_stopped: boolean;
                            escalation_level: number;
                            virtual_age_months: number;
                            current_video_url: string | null;
                        };
                        child: {
                            id: number;
                            name: string;
                        };
                        /** @enum {string} */
                        traffic_light: "green" | "amber" | "red";
                        quiet_hours: {
                            school_start: string | null;
                            school_end: string | null;
                            bedtime_start: string | null;
                            bedtime_end: string | null;
                            is_active: boolean;
                        } | null;
                        recent_activities: {
                            id: number;
                            activity_type: string;
                            value: number | null;
                            created_at: string;
                            is_positive: boolean;
                        }[];
                        weekly_performance: {
                            date: string;
                            completed: number;
                            missed: number;
                        }[];
                    } | {
                        /** @constant */
                        message: "No active pet session found.";
                        pet: null;
                        /** @constant */
                        traffic_light: "green";
                        quiet_hours: components["schemas"]["QuietHours"];
                        recent_activities: string[];
                    } | {
                        /** @constant */
                        message: "No child profile paired yet.";
                        pet: null;
                        /** @constant */
                        traffic_light: "green";
                        quiet_hours: null;
                        recent_activities: string[];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Only parent profiles can access the dashboard.";
                    };
                };
            };
        };
    };
    "parentDashboard.activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: number;
                            activity_type: string;
                            value: number | null;
                            created_at: string;
                            is_positive: boolean;
                        }[];
                        meta: {
                            current_page: number;
                            last_page: number;
                            total: number;
                        };
                    } | {
                        data: string[];
                        meta: {
                            /** @constant */
                            current_page: 1;
                            /** @constant */
                            last_page: 1;
                            total: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Only parent profiles can access activities.";
                    };
                };
            };
        };
    };
    "parentDashboard.toggleHardStop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        message: "Hard stop activated. Child app locked." | "Hard stop deactivated. Child app unlocked.";
                        is_hard_stopped: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Only parent profiles can trigger hard stop.";
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "No active pet session found.";
                    } | {
                        /** @constant */
                        message: "No child profile paired.";
                    };
                };
            };
        };
    };
    "quietHours.show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        quiet_hours: {
                            id: number;
                            school_start: string | null;
                            school_end: string | null;
                            bedtime_start: string | null;
                            bedtime_end: string | null;
                            is_active: boolean;
                        };
                    } | {
                        /** @constant */
                        message: "No quiet hours configured.";
                        quiet_hours: null;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Only parent profiles can manage quiet hours.";
                    };
                };
            };
        };
    };
    "quietHours.update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateQuietHoursRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Quiet hours updated successfully.";
                        quiet_hours: {
                            id: number;
                            school_start: string | null;
                            school_end: string | null;
                            bedtime_start: string | null;
                            bedtime_end: string | null;
                            is_active: boolean;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Only parent profiles can manage quiet hours.";
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "revenueCatWebhook.handle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevenueCatWebhookRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Purchase recorded.";
                        revenuecat_id: string | null;
                    } | {
                        /** @constant */
                        message: "Border Collie breed unlocked successfully.";
                        pet_id: number;
                        breed_type: string;
                    } | {
                        /** @constant */
                        message: "Event ignored.";
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Unauthorized";
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "User not found.";
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
}
