<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * M5-R03 (David 2026-10-06): training ("šolanje") — a daily reward-timing
 * mini-game per command (sit, come, place, potty), progress 0–100 % per
 * command, a daily routine in the Care Score.
 *
 *  - pets.training_enabled: set once at creation when the PIN had a profile
 *    AND both the parent's generate-pin and the child's pin-login declared
 *    `features: ["training"]` (ClientFeature). Every existing pet: false.
 *  - pets.training_learning_factor: the pet's individual learning factor
 *    (mixed breed ±20 %, David 2026-10-06), drawn once from a seeded RNG and
 *    stored, so it never changes for that dog.
 *  - pets.training_decayed_through: last family-local day whose "no
 *    practice → progress decays" rule was applied (TrainingService).
 *  - pet_training_skills: one row per (pet, command) with progress (double,
 *    0–100, rounded only for output) and the last completed session.
 *  - pet_training_sessions: server-authoritative sessions (schedule of cues /
 *    obey instants generated by the server, taps scored against it). At most
 *    one active session per pet (partial unique index); `interrupted` = a
 *    lock began during the session (not counted, its time refunded). `user_id` = the
 *    child who trains (null after the child profile is deleted).
 *  - activities_log: `trained_pet` (a completed session = the day's
 *    training routine, value = correctly timed praises).
 *  - pet_daily_routines.routine_type: + `training`.
 *  - breed_stage_params keys: the training numbers (BreedStageParamsSeeder).
 *
 * Additive; down() removes the new rows / columns and restores the checks.
 */
return new class extends Migration
{
    private const ACTIVITY_TYPES_OLD = "'fed_pet', 'watered_pet', 'walked_pet', 'cleaned_poop', 'ignored_warning', 'signed_contract', 'parent_fed_pet', "
        ."'took_out_pet', 'resolved_chewing', 'pet_accident', 'pet_chewed'";

    private const ACTIVITY_TYPES_NEW = self::ACTIVITY_TYPES_OLD.", 'trained_pet'";

    private const ROUTINES_OLD = "'feed', 'water', 'clean', 'walk'";

    private const ROUTINES_NEW = self::ROUTINES_OLD.", 'training'";

    private const KEYS_OLD = "'starts_at_months', 'arrival_age_months', 'meals_per_day', 'feed_windows', "
        ."'exercise_minutes_per_day', 'exercise_minutes_per_age_month', 'sleep_hours', "
        ."'steps_per_exercise_minute', 'adult_weight_kg', 'house_trained_by_months', 'teething_months', "
        ."'growth_end_months', 'coren_rank', 'lifespan_years', 'accident_hold_hours_per_age_month', 'chewing_chance_per_day'";

    private const NEW_KEYS = ['training_learning_multiplier', 'training_individual_variation', 'training_minutes_per_day',
        'training_progress_per_success', 'training_decay_per_missed_day', 'potty_training_accident_reduction',
        'place_training_chewing_reduction'];

    private const COMMANDS = "'sit', 'come', 'place', 'potty'";

    public function up(): void
    {
        Schema::table('pets', function (Blueprint $table) {
            $table->boolean('training_enabled')->default(false);
            $table->double('training_learning_factor')->nullable();
            $table->date('training_decayed_through')->nullable();
        });

        Schema::create('pet_training_skills', function (Blueprint $table) {
            $table->id();
            $table->foreignId('pet_id')->constrained('pets')->cascadeOnDelete();
            $table->string('command', 16);
            $table->double('progress')->default(0);
            $table->timestamp('last_practised_at')->nullable();
            $table->unsignedInteger('sessions_completed')->default(0);
            $table->timestamps();

            $table->unique(['pet_id', 'command']);
        });
        DB::statement('ALTER TABLE pet_training_skills ADD CONSTRAINT pet_training_skills_command_check CHECK (command IN ('.self::COMMANDS.'))');
        DB::statement('ALTER TABLE pet_training_skills ADD CONSTRAINT pet_training_skills_progress_check CHECK (progress >= 0 AND progress <= 100)');

        Schema::create('pet_training_sessions', function (Blueprint $table) {
            $table->id();
            $table->uuid('public_id')->unique();
            $table->foreignId('pet_id')->constrained('pets')->cascadeOnDelete();
            $table->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete();
            $table->string('command', 16);
            $table->date('local_date');
            $table->timestamp('started_at');
            $table->timestamp('ends_at');
            $table->timestamp('expires_at');
            $table->unsignedInteger('duration_ms');
            $table->jsonb('schedule');
            $table->string('status', 16)->default('active');
            $table->timestamp('finished_at')->nullable();
            $table->jsonb('taps')->nullable();
            $table->jsonb('result')->nullable();
            $table->double('progress_before')->nullable();
            $table->double('progress_gain')->nullable();
            $table->timestamps();

            $table->index(['pet_id', 'local_date']);
        });
        DB::statement('ALTER TABLE pet_training_sessions ADD CONSTRAINT pet_training_sessions_command_check CHECK (command IN ('.self::COMMANDS.'))');
        DB::statement("ALTER TABLE pet_training_sessions ADD CONSTRAINT pet_training_sessions_status_check CHECK (status IN ('active', 'completed', 'expired', 'interrupted'))");
        DB::statement("CREATE UNIQUE INDEX pet_training_sessions_one_active ON pet_training_sessions (pet_id) WHERE status = 'active'");

        DB::statement('ALTER TABLE activities_log DROP CONSTRAINT IF EXISTS activities_log_activity_type_check');
        DB::statement('ALTER TABLE activities_log ADD CONSTRAINT activities_log_activity_type_check CHECK (activity_type IN ('.self::ACTIVITY_TYPES_NEW.'))');

        DB::statement('ALTER TABLE pet_daily_routines DROP CONSTRAINT IF EXISTS pet_daily_routines_type_check');
        DB::statement('ALTER TABLE pet_daily_routines ADD CONSTRAINT pet_daily_routines_type_check CHECK (routine_type IN ('.self::ROUTINES_NEW.'))');

        DB::statement('ALTER TABLE breed_stage_params DROP CONSTRAINT IF EXISTS breed_stage_params_key_check');
        DB::statement('ALTER TABLE breed_stage_params ADD CONSTRAINT breed_stage_params_key_check CHECK (key IN ('.self::KEYS_OLD.", '".implode("', '", self::NEW_KEYS)."'))");
    }

    public function down(): void
    {
        DB::table('breed_stage_params')->whereIn('key', self::NEW_KEYS)->delete();
        DB::statement('ALTER TABLE breed_stage_params DROP CONSTRAINT IF EXISTS breed_stage_params_key_check');
        DB::statement('ALTER TABLE breed_stage_params ADD CONSTRAINT breed_stage_params_key_check CHECK (key IN ('.self::KEYS_OLD.'))');

        DB::table('pet_daily_routines')->where('routine_type', 'training')->delete();
        DB::statement('ALTER TABLE pet_daily_routines DROP CONSTRAINT IF EXISTS pet_daily_routines_type_check');
        DB::statement('ALTER TABLE pet_daily_routines ADD CONSTRAINT pet_daily_routines_type_check CHECK (routine_type IN ('.self::ROUTINES_OLD.'))');

        DB::table('activities_log')->where('activity_type', 'trained_pet')->delete();
        DB::statement('ALTER TABLE activities_log DROP CONSTRAINT IF EXISTS activities_log_activity_type_check');
        DB::statement('ALTER TABLE activities_log ADD CONSTRAINT activities_log_activity_type_check CHECK (activity_type IN ('.self::ACTIVITY_TYPES_OLD.'))');

        Schema::dropIfExists('pet_training_sessions');
        Schema::dropIfExists('pet_training_skills');

        Schema::table('pets', function (Blueprint $table) {
            $table->dropColumn(['training_enabled', 'training_learning_factor', 'training_decayed_through']);
        });
    }
};
