<?php

namespace App\Enums;

/**
 * Represents the visual/behavioral state of a pet.
 * Each state maps to a state video generated by fal.ai (Kling 3.0 Pro, M4-03) and
 * stored in pet_media.
 */
enum PetStateEnum: string
{
    case Idle = 'idle';
    case Sleeping = 'sleeping';
    case LowEnergy = 'low_energy';
    case Hungry = 'hungry';
    case Sick = 'sick';
    case Playing = 'playing';

    /**
     * Get a human-readable description of the pet state.
     */
    public function description(): string
    {
        return match ($this) {
            self::Idle => 'Pet is relaxed and alert',
            self::Sleeping => 'Pet is sleeping peacefully',
            self::LowEnergy => 'Pet looks tired and lethargic',
            self::Hungry => 'Pet is staring at its food bowl',
            self::Sick => 'Pet looks unwell and greyed out',
            self::Playing => 'Pet is energetic and playful',
        };
    }

    /**
     * What the dog does in this state's video (M4-03). Combined with the pet's
     * DNA description by PetAppearancePrompt::videoPrompt(). Subtle, realistic
     * motion only — the video loops behind the HUD; the app adds UI effects
     * (e.g. the grey "sick" overlay) itself.
     */
    public function promptModifier(): string
    {
        return match ($this) {
            self::Idle => 'sitting calmly and looking around with a relaxed expression, gentle breathing, an occasional slow tail wag and ear twitch',
            self::Sleeping => 'curled up asleep on the floor, eyes closed, slow rhythmic breathing, a small ear twitch',
            self::LowEnergy => 'lying down with droopy eyelids, head resting on the front paws, slow tired breathing, barely moving',
            self::Hungry => 'sitting next to an empty dog food bowl, looking down at it and then up hopefully, licking its lips',
            self::Sick => 'lying down quietly with sad tired eyes, head low, slow shallow breathing, not getting up',
            self::Playing => 'in a playful bow with the tail wagging, bouncing gently on the front paws in place, happy open mouth',
        };
    }
}
