<?php

namespace App\Enums;

/**
 * Represents the visual/behavioral state of a pet.
 * Each state maps to a specific video asset generated by fal.ai (Kling 3.0).
 */
enum PetStateEnum: string
{
    case Idle = 'idle';
    case Sleeping = 'sleeping';
    case LowEnergy = 'low_energy';
    case Hungry = 'hungry';
    case Sick = 'sick';
    case Playing = 'playing';

    /**
     * Get a human-readable description of the pet state.
     */
    public function description(): string
    {
        return match ($this) {
            self::Idle => 'Pet is relaxed and alert',
            self::Sleeping => 'Pet is sleeping peacefully',
            self::LowEnergy => 'Pet looks tired and lethargic',
            self::Hungry => 'Pet is staring at its food bowl',
            self::Sick => 'Pet looks unwell and greyed out',
            self::Playing => 'Pet is energetic and playful',
        };
    }

    /**
     * Get the video generation prompt modifier for this state.
     * This is combined with the pet's prompt_anchor to generate
     * a state-specific video on fal.ai.
     */
    public function promptModifier(): string
    {
        return match ($this) {
            self::Idle => 'sitting calmly, looking around with a relaxed expression, gentle breathing',
            self::Sleeping => 'curled up sleeping, eyes closed, slow rhythmic breathing, peaceful',
            self::LowEnergy => 'lying down with droopy eyes, slow movements, looking exhausted',
            self::Hungry => 'staring intently at an empty food bowl, whining, pawing at the bowl',
            self::Sick => 'lying down with a dull greyish tint, lethargic, refusing to move, sad eyes',
            self::Playing => 'running joyfully, tail wagging, bouncing with energy, playful expression',
        };
    }
}
