<?php

namespace App\Enums;

use InvalidArgumentException;

/**
 * Represents the visual/behavioral state of a pet.
 * Each state maps to a state video generated by fal.ai (Kling 3.0 Pro, M4-03) and
 * stored in pet_media.
 *
 * Species (M5-R06-07, CAT_SPEC §8): the six classic states exist for both
 * species with their own video prompt (a cat's `low_energy` is "bored" —
 * its energy is the play meter). Behaviour videos are per species: dogs
 * `accident` / `chewing`, cats `scratching` (appliesTo()).
 */
enum PetStateEnum: string
{
    case Idle = 'idle';
    case Sleeping = 'sleeping';
    case LowEnergy = 'low_energy';
    case Hungry = 'hungry';
    case Sick = 'sick';
    case Playing = 'playing';

    // M5-R02 behaviour videos (premium set only, MediaEntitlementService).
    // `pets.pet_state` never takes these values: a dirty dog stays `sick`
    // (old app builds know only the six states); the apps pick these videos
    // from the payload's `behaviour.scene` while such an event is open.
    case Accident = 'accident';
    case Chewing = 'chewing';

    // M5-R06-07: the cat's behaviour video ("opraskala je kavč", CAT_SPEC Q10),
    // shown while a scratching mess is open (`behaviour.scene` = scratching).
    // Video slots only — never a `pets.pet_state` value. No `accident` for cats.
    case Scratching = 'scratching';

    /**
     * The values `pets.pet_state` can take (pets_pet_state_check): the six
     * classic states. Behaviour states are video slots only.
     *
     * @return list<self>
     */
    public static function petStates(): array
    {
        return [self::Idle, self::Sleeping, self::LowEnergy, self::Hungry, self::Sick, self::Playing];
    }

    /** A behaviour video (M5-R02 / M5-R06-07) — shown from `behaviour.scene`, gated by MediaEntitlementService. */
    public function isBehaviour(): bool
    {
        return in_array($this, [self::Accident, self::Chewing, self::Scratching], true);
    }

    /** Whether a pet of the species can ever show this state (and get its video). */
    public function appliesTo(Species $species): bool
    {
        return match ($this) {
            self::Accident, self::Chewing => $species === Species::Dog,
            self::Scratching => $species === Species::Cat,
            default => true,
        };
    }

    /**
     * Get a human-readable description of the pet state.
     */
    public function description(): string
    {
        return match ($this) {
            self::Idle => 'Pet is relaxed and alert',
            self::Sleeping => 'Pet is sleeping peacefully',
            self::LowEnergy => 'Pet looks tired and lethargic',
            self::Hungry => 'Pet is staring at its food bowl',
            self::Sick => 'Pet looks unwell and greyed out',
            self::Playing => 'Pet is energetic and playful',
            self::Accident => 'Puppy had an accident indoors (puddle)',
            self::Chewing => 'Dog is chewing a slipper',
            self::Scratching => 'Cat is scratching the sofa',
        };
    }

    /**
     * What the dog does in this state's video (M4-03). Combined with the pet's
     * DNA description by PetAppearancePrompt::videoPrompt(). Subtle, realistic
     * motion only — the video loops behind the HUD; the app adds UI effects
     * (e.g. the grey "sick" overlay) itself.
     *
     * Cats (M5-R06-07, CAT_SPEC §8 "videi stanj" — draft (D)): their own
     * modifiers. A state the species never has throws.
     */
    public function promptModifier(Species $species = Species::Dog): string
    {
        if (! $this->appliesTo($species)) {
            throw new InvalidArgumentException("A {$species->value} has no '{$this->value}' video.");
        }

        if ($species === Species::Cat) {
            return match ($this) {
                self::Idle => 'sitting calmly and looking around, blinking slowly, the tail gently curling and moving, an occasional ear twitch',
                self::Sleeping => 'curled up in a tight ball asleep on a soft blanket, eyes closed, slow rhythmic breathing, a small ear twitch',
                // Energy is the play meter for a cat (M5-R06-04): low = bored, not tired.
                self::LowEnergy => 'lying on a windowsill and gazing out of the window with a bored expression, the tail tip slowly flicking, barely moving',
                self::Hungry => 'sitting next to an empty cat food bowl, looking down at it and then up expectantly, licking its lips',
                // No distressing scenes (CAT_SPEC §8).
                self::Sick => 'lying quietly in a hunched loaf position with half-closed eyes, slow calm breathing, not getting up',
                // The toy hangs from above — no hand, no person in frame.
                self::Playing => 'leaping and batting with its front paws at a feather toy dangling on a string from above the frame, playful and alert',
                self::Scratching => 'standing on its hind legs and scratching the side of a fabric sofa with its front claws, stretching, focused',
                self::Accident, self::Chewing => throw new InvalidArgumentException("A cat has no '{$this->value}' video."),
            };
        }

        return match ($this) {
            self::Idle => 'sitting calmly and looking around with a relaxed expression, gentle breathing, an occasional slow tail wag and ear twitch',
            self::Sleeping => 'curled up asleep on the floor, eyes closed, slow rhythmic breathing, a small ear twitch',
            self::LowEnergy => 'lying down with droopy eyelids, head resting on the front paws, slow tired breathing, barely moving',
            self::Hungry => 'sitting next to an empty dog food bowl, looking down at it and then up hopefully, licking its lips',
            self::Sick => 'lying down quietly with sad tired eyes, head low, slow shallow breathing, not getting up',
            self::Playing => 'in a playful bow with the tail wagging, bouncing gently on the front paws in place, happy open mouth',
            self::Accident => 'standing next to a small clear puddle on a wooden floor, looking up with a guilty apologetic expression, ears slightly back, a slow low tail wag',
            self::Chewing => 'lying on the floor chewing a soft house slipper held between the front paws, focused and playful, an occasional tail wag',
            self::Scratching => throw new InvalidArgumentException('A dog has no scratching video.'),
        };
    }
}
